logConfig:
  code: zerolog
  level: trace
  enableCaller: true
  enablePrettyPrint: true

dataStoresConfig:
  dbConfig: &dbConfig
    code: sql
    driverName: postgres
    host: localhost
    port: 5432
    dbName: testdb
    user: ${SQL_USER}
    password: ${SQL_PASSWORD}
    tx: false
  mqConfig: &mqConfig
    code: nats
    url: nats://localhost:4222

apisConfig:
  address: 0.0.0.0
  port: 8080
  root: /
  restConfig:
    code: rest
    enabled: true
    path: api/
  mqConfig: 
    code: nats
    stream: USERS_REQ
    createUserSubject: USER.CREATE
    config: *mqConfig

usecasesConfig:
  manageUsersUsecaseConfig:
    code: manageUsers
    dbDataServiceConfig:
      code: dbData
      dataStoreConfig: *dbConfig
    mqDataServiceConfig:
      code: mqData
      streamName: USERS
      userCreatedSubject: USER.CREATED
      dataStoreConfig: *mqConfig
